# Generated by Django 6.0 on 2026-01-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Workshop', 'Workshop'), ('Celebration', 'Celebration')], default='Academic', max_length=50),
        ),
    ]
