# Generated by Django 6.0 on 2026-01-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissioninquiry_gender_admissioninquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioninquiry',
            name='previous_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
