# Generated by Django 6.0 on 2025-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('current_position', models.CharField(blank=True, max_length=200, null=True)),
                ('position_teaching', models.BooleanField(default=False, verbose_name='Position: Teaching')),
                ('position_non_teaching', models.BooleanField(default=False, verbose_name='Position: Non-Teaching')),
                ('position_admin', models.BooleanField(default=False, verbose_name='Position: Office Administration')),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('less_than_1', 'Less than 1 year'), ('1_to_5', '1–5 years'), ('above_5', 'Above 5 years')], max_length=50)),
                ('resume', models.FileField(upload_to='careers/resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Interview', 'Interview'), ('Rejected', 'Rejected')], default='New', max_length=20)),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(choices=[('admissions', 'Admissions Inquiry'), ('general', 'General Question'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
