# Generated by Django 6.0 on 2026-01-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='pg_qualification',
            field=models.CharField(default='N/A', max_length=200, verbose_name='PG Qualification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='professional_degree',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Professional Degree (B.Ed/D.Ed)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='ug_qualification',
            field=models.CharField(default='N/A', max_length=200, verbose_name='UG Qualification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female')], default='Female', max_length=20),
        ),
    ]
