# Generated by Django 6.0 on 2026-01-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_careerapplication_pg_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='pg_qualification',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='ug_qualification',
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='qualification',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Academic Qualification'),
            preserve_default=False,
        ),
    ]
