import React, { useEffect, useState } from 'react';
import { FaBookOpen, FaBullseye, FaChartLine, FaAward, FaUsers, FaGlobe, FaCheckCircle, FaDownload } from 'react-icons/fa';

const Curriculum = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const [expandedStage, setExpandedStage] = useState(null);

    const toggleStage = (index) => {
        setExpandedStage(expandedStage === index ? null : index);
    };

    const handleDownload = () => {
        import('jspdf').then(({ default: jsPDF }) => {
            const doc = new jsPDF();
            const margin = 20;
            let yPos = 30;

            // Header - School Name
            doc.setFontSize(24);
            doc.setTextColor(255, 110, 48); // Primary Color (Orange)
            doc.text("NETHAJI VIDYALAYAM", 105, yPos, { align: "center" });

            yPos += 15;

            // Subheader - Handbook Title
            doc.setFontSize(18);
            doc.setTextColor(30, 36, 110); // Secondary Color (Navy Blue)
            doc.text("Curriculum Handbook", 105, yPos, { align: "center" });

            yPos += 20;

            curriculumStages.forEach((stage) => {
                // Check if we need a new page
                if (yPos > 240) {
                    doc.addPage();
                    yPos = 30;
                }

                // Stage Level
                doc.setFontSize(14);
                doc.setTextColor(30, 36, 110);
                doc.setFont("helvetica", "bold");
                doc.text(stage.level.toUpperCase(), margin, yPos);

                yPos += 8;

                // Focus
                doc.setFontSize(11);
                doc.setTextColor(100, 100, 100);
                doc.setFont("helvetica", "italic");
                doc.text(`Focus: ${stage.focus}`, margin, yPos);

                yPos += 10;

                // Details
                if (stage.details && stage.details.length > 0) {
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(10);
                    doc.setTextColor(60, 60, 60);

                    stage.details.forEach((detail) => {
                        const itemText = `${detail.category}: ${detail.items}`;
                        const splitText = doc.splitTextToSize(itemText, 170);

                        // Check for page break within details
                        if (yPos + (splitText.length * 5) > 280) {
                            doc.addPage();
                            yPos = 30;
                        }

                        doc.text("•", margin, yPos);
                        doc.text(splitText, margin + 5, yPos);

                        yPos += (splitText.length * 5) + 2;
                    });
                }

                yPos += 10;
                // Divider line
                doc.setDrawColor(230, 230, 230);
                doc.line(margin, yPos, 190, yPos);
                yPos += 15;
            });

            // Footer
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text("Generated by Nethaji Vidyalayam Digital Portal", 105, 285, { align: "center" });

            doc.save("Nethaji_Vidyalayam_Curriculum_Handbook.pdf");
        });
    };

    const pillars = [
        {
            icon: <FaBookOpen size={32} />,
            title: "Academic Rigor",
            desc: "Challenging, research-based curriculum aligned with CBSE standards.",
            color: "from-orange-500 to-red-500"
        },
        {
            icon: <FaUsers size={32} />,
            title: "Character Development",
            desc: "Emphasis on values, ethics, and social responsibility.",
            color: "from-red-500 to-pink-500"
        },
        {
            icon: <FaGlobe size={32} />,
            title: "Global Perspective",
            desc: "Exposure to diverse cultures, languages, and worldviews.",
            color: "from-purple-500 to-indigo-500"
        },
        {
            icon: <FaChartLine size={32} />,
            title: "Skill-Based Learning",
            desc: "Focus on critical thinking, creativity, and problem-solving.",
            color: "from-blue-500 to-cyan-500"
        }
    ];

    const curriculumStages = [
        {
            level: "Foundational Stage (Pre-KG)",
            focus: "Play-based Learning, Phonics, Basic Numeracy, Motor Skills",
            color: "bg-green-50 border-green-200",
            btnColor: "text-green-600",
            details: [
                { category: "Language", items: "Listening skills, action songs, rhymes, vocabulary" },
                { category: "Numbers", items: "Number recognition, counting (1–10)" },
                { category: "Environmental Awareness", items: "Self, family, colours, fruits, animals" },
                { category: "Motor Skills", items: "Scribbling, finger movements, play activities" },
                { category: "Art & Craft", items: "Colouring, tearing & pasting" },
                { category: "Physical Activities", items: "Free play, music & movement" },
                { category: "Social Skills", items: "Sharing, following instructions" }
            ]
        },
        {
            level: "Preparatory Stage (LKG)",
            focus: "Core Subjects (Languages, Math, EVS), Discovery Learning, Reading Habits",
            color: "bg-blue-50 border-blue-200",
            btnColor: "text-blue-600",
            details: [
                { category: "Language", items: "Alphabet recognition, phonics, simple words, rhymes" },
                { category: "Numbers", items: "Counting (1–50), number writing, shapes, patterns" },
                { category: "Environmental Studies", items: "Home, school, community helpers, plants" },
                { category: "Writing Skills", items: "Pre-writing strokes, tracing, colouring" },
                { category: "Art & Craft", items: "Drawing, creative activities" },
                { category: "Physical Education", items: "Games, yoga, coordination activities" },
                { category: "Life Skills", items: "Manners, cleanliness, safety habits" }
            ]
        },
        {
            level: "Middle Stage (UKG)",
            focus: "Subject Specialization (Science, Social Studies), Critical Thinking, Project Work",
            color: "bg-purple-50 border-purple-200",
            btnColor: "text-purple-600",
            details: [
                { category: "Language", items: "Reading simple sentences, sight words, storytelling" },
                { category: "Mathematics", items: "Numbers (1–100), addition & subtraction (basic)" },
                { category: "Environmental Studies", items: "Seasons, transport, festivals, animals" },
                { category: "Writing Skills", items: "Sentence writing, spelling, worksheets" },
                { category: "Science Basics", items: "Living & non-living things, day & night" },
                { category: "Art & Craft", items: "Theme-based creative work" },
                { category: "Physical Education", items: "Sports, drills, yoga" },
                { category: "Life Skills", items: "Independence, teamwork, responsibility" }
            ]
        },
        {
            level: "Secondary Stage (Grade 1 to 5)",
            focus: "Core Academics, Life Skills, Holistic Growth",
            color: "bg-orange-50 border-orange-200",
            btnColor: "text-orange-600",
            details: [
                { category: "Languages", items: "English, Tamil/Hindi (Grammar, Creative Writing, Literature)" },
                { category: "Mathematics", items: "Arithmetic operations, Geometry, Data handling, Word problems" },
                { category: "EVS / Science", items: "Grades 1-3: Environmental Studies; Grades 4-5: General Science" },
                { category: "Social Studies", items: "Grades 4-5: History, Geography, Civics, Indian Heritage" },
                // { category: "ICT & Coding", items: "Digital literacy, basic programming concepts" },
                { category: "Life Skills", items: "Value education, personality development, leadership" },
                { category: "Extracurricular", items: "Yoga, Performing Arts, Sports, Science Club" }
            ]
        }
    ];

    const assessmentFramework = [
        { type: "Formative Assessment", weight: "40%", desc: "Quizzes, Projects, Class Participation" },
        { type: "Summative Assessment", weight: "60%", desc: "Mid-Term & Final Exams" }
    ];

    return (
        <div className="font-sans bg-gray-50 text-gray-800">
            {/* Hero */}
            <section className="relative h-[400px] flex items-center justify-center text-white overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-br from-orange-500 via-pink-500 to-purple-600 opacity-90 z-10"></div>
                <div
                    className="absolute inset-0 bg-cover bg-center z-0"
                    style={{ backgroundImage: "url('https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80')" }}
                ></div>
                <div className="relative z-20 container mx-auto px-4 text-center">
                    <h1 className="text-5xl md:text-6xl font-bold mb-6 tracking-tight">Our Curriculum</h1>
                    <p className="text-xl md:text-2xl text-gray-200 mobile-subtitle max-w-2xl mx-auto font-light">A Modern, Holistic Approach to Education</p>
                </div>
            </section>

            {/* Philosophy */}
            <section className="py-20 bg-white">
                <div className="container mx-auto px-4 max-w-4xl text-center">
                    <span className="inline-block px-4 py-1.5 rounded-full bg-primary/10 text-primary font-bold text-sm tracking-widest uppercase mb-4">Educational Philosophy</span>
                    <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-8 leading-tight">Learning for Life</h2>
                    <p className="text-gray-600 text-lg md:text-xl leading-relaxed mb-6">
                        Our curriculum is designed to foster critical thinking, creativity, and a global mindset through innovative teaching methodologies and value-based education.
                    </p>
                    <p className="text-gray-600 text-lg md:text-xl leading-relaxed">
                        Our approach is student-centered, inquiry-based, and rooted in the principles of constructivism. We aim to cultivate lifelong learners who are curious, compassionate, and confident.
                    </p>
                </div>
            </section>

            {/* Four Pillars */}
            <section className="py-20 bg-gray-50">
                <div className="container mx-auto px-4">
                    <div className="text-center mb-16">
                        <h2 className="text-3xl font-bold text-secondary mb-4">Four Pillars of Our Curriculum</h2>
                        <p className="text-gray-600">Education that balances intellect, emotion, and ethics.</p>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                        {pillars.map((pillar, index) => (
                            <div key={index} className="bg-white p-8 rounded-xl border-t-4 border-primary shadow-[0_10px_30px_-15px_rgba(0,0,0,0.1)] overflow-hidden flex flex-col items-center text-center group hover:-translate-y-2 transition-all duration-300">

                                {/* Icon Container */}
                                <div className="w-20 h-20 bg-gradient-to-br from-[#d36449] to-[#453c6d] text-white rounded-full mb-8 flex items-center justify-center shadow-[0_8px_20px_-5px_rgba(0,0,0,0.2)] transform group-hover:scale-110 transition-transform duration-300">
                                    {React.cloneElement(pillar.icon, { size: 30 })}
                                </div>

                                <h3 className="text-xl font-bold text-[#1e3a8a] mb-4">{pillar.title}</h3>
                                <p className="text-gray-500 leading-relaxed text-sm px-2">{pillar.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Curriculum Structure */}
            <section className="py-20 bg-white">
                <div className="container mx-auto px-4 max-w-6xl">
                    <div className="text-center mb-16">
                        <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Curriculum Structure</h2>
                        <p className="text-gray-600 text-lg">Comprehensive coverage across all grade levels.</p>
                    </div>
                    <div className="grid gap-6">
                        {curriculumStages.map((stage, index) => (
                            <div key={index} className={`rounded-2xl border transition-all duration-300 ${stage.color} ${expandedStage === index ? 'shadow-md scale-[1.01]' : 'shadow-sm hover:shadow-md'}`}>
                                <div className="p-6 lg:p-8 flex flex-col lg:flex-row items-center gap-6">
                                    <div className="flex-1 text-center lg:text-left">
                                        <h3 className="text-2xl font-bold text-gray-800 mb-2">{stage.level}</h3>
                                        <p className="text-gray-600 font-medium">{stage.focus}</p>
                                    </div>
                                    <button
                                        onClick={() => toggleStage(index)}
                                        className={`px-6 py-3 rounded-xl font-bold bg-white shadow-sm border border-gray-100 flex items-center gap-2 transition-all hover:bg-gray-50 ${stage.btnColor}`}
                                    >
                                        {expandedStage === index ? 'Hide Details' : 'View Details'}
                                        <FaBullseye className={`transition-transform duration-300 ${expandedStage === index ? 'rotate-180' : ''}`} size={16} />
                                    </button>
                                </div>

                                {expandedStage === index && stage.details && stage.details.length > 0 && (
                                    <div className="px-6 lg:px-8 pb-8 pt-2 border-t border-gray-200/50">
                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">
                                            {stage.details.map((detail, idx) => (
                                                <div key={idx} className="bg-white/60 p-4 rounded-xl border border-gray-100">
                                                    <h4 className={`font-bold text-sm uppercase tracking-wide mb-2 ${stage.btnColor}`}>{detail.category}</h4>
                                                    <p className="text-gray-700 text-sm leading-relaxed">{detail.items}</p>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Assessment */}
            <section className="py-20 bg-secondary text-white">
                <div className="container mx-auto px-4 max-w-4xl">
                    <div className="text-center mb-12">
                        <h2 className="text-3xl font-bold mb-4">Assessment Framework</h2>
                        <p className="text-gray-200">Continuous evaluation for holistic growth.</p>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
                        {assessmentFramework.map((item, index) => (
                            <div key={index} className="bg-white/10 backdrop-blur-sm p-8 rounded-xl border border-white/20">
                                <FaAward className="text-primary mb-4" size={32} />
                                <h3 className="text-2xl font-bold mb-2">{item.type}</h3>
                                <span className="inline-block bg-primary text-white px-4 py-1 rounded-full text-sm font-bold mb-4">{item.weight}</span>
                                <p className="text-gray-200">{item.desc}</p>
                            </div>
                        ))}
                    </div>
                    <div className="bg-white/10 backdrop-blur-sm p-6 rounded-xl border border-white/20">
                        <h4 className="font-bold text-lg mb-3">Key Assessment Features:</h4>
                        <ul className="space-y-2">
                            {[
                                "Activity-based learning",
                                "Worksheets and projects",
                                "Periodic assessments",
                                "Continuous observation and feedback"
                            ].map((feature, idx) => (
                                <li key={idx} className="flex items-start gap-2">
                                    <FaCheckCircle size={18} className="text-primary mt-1 shrink-0" />
                                    <span>{feature}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </section>

            {/* Download CTA */}
            <section className="py-16 bg-white text-center">
                <div className="container mx-auto px-4">
                    <h2 className="text-3xl font-bold text-gray-900 mb-6">Want to Know More?</h2>
                    <p className="text-gray-600 mb-8 max-w-2xl mx-auto">
                        Download our detailed curriculum handbook for a comprehensive overview of grade-wise syllabi, learning outcomes, and teaching methodologies.
                    </p>
                    <button
                        onClick={handleDownload}
                        className="inline-flex items-center gap-2 bg-primary hover:bg-primary-hover text-white px-10 py-4 rounded-full font-bold shadow-lg transition-all"
                    >
                        <FaDownload size={20} /> Download Curriculum Handbook
                    </button>
                </div>
            </section>
        </div>
    );
};

export default Curriculum;
